### ISSUE TITLE
Feature request: Avoidance of double users imports

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2253] opened 2016-08-04 13:10 UTC
**Issue:** If a csv of users is imported twice, all the users are imported twice, and have two similar entries as different accounts. It can easily happen, and there is no rollback possible.

**Desired behaviour:** Loop through the users to be imported. If certain information is identical (`first name & last name & number` ?), there should be a table/dialog with the matching cases, offering the following options:

a) keep the original, discard the new entry
b) keep the new entry, discard the original
c) keep both entries as separate entities
further option) do [(a/b/c)] for all cases or only selected.

**Comment by emanuelschuetze** [comment] 2016-08-10 10:35
Closed. Duplicate of #1213.

**Closed by emanuelschuetze** 2016-08-10 10:35 UTC
Labels: duplicate
