### ISSUE TITLE
import/export of motions changes formatting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3067] opened 2017-03-08 00:14 UTC
OS offers a CSV file to see how motion  are added to a CSV import file. So let's test it:

- download the offered CSV example file
- use this file for an import
- now export the resulting motionss

result: the exported CSV looks different (`<p>` statements, quotation marks etc.)

The example file of OS 2.1 b3 is this one:
[motions-example.txt](https://github.com/OpenSlides/OpenSlides/files/826234/motions-example.txt)
and this is what one gets after the export:
[motions-export.txt](https://github.com/OpenSlides/OpenSlides/files/826235/motions-export.txt)

expected result: the exported file is identic to the imported file because nothing has been changed in the meantime.

**Comment by donovaly** [comment] 2017-03-08 00:17
The same bug occurs when importing/exporting participants.

**Comment by FinnStutzenstein** [comment] 2017-03-08 05:14
I think this is not really a bug. We show the user how simply he can import things without think about the right formatting, setting all tags and also could have different forms of the csv. OS takes care about all this things for you. Also the export could be different, because OS exports correct CSV (see RFC 4180), but you can import slightly different formats. We have a powerful parser who can handel this.

**Comment by donovaly** [comment] 2017-03-09 23:06
> Also the export could be different, because OS exports correct CSV

That might be but my experience is that import/export roundtrips often cause problems. By assuring that nothing is changed when using the example CSV files for an import, you also have a nice test that the parser works correct. I use this test for all releases of OS and found this way already some bugs.

**Comment by emanuelschuetze** [comment] 2017-03-21 14:07
I tested the motion import (of example file) and export these motions:
Both csv files contains the same motions. I can reimport the export file successfully and get the same motions. Only the formatting of csv export file is slightly different from original example file (which contains e.g. no ".." for each field), But theses changes does not influence the motions.

So it is not a bug. (won't fix)

**Closed by emanuelschuetze** 2017-03-21 14:07 UTC

**Comment by donovaly** [comment] 2017-03-25 16:44
> Only the formatting of csv export file is slightly different from original example file (which contains e.g. no ".." for each field)

But this is what I meant. To repeat my comment "By assuring that _nothing_ is changed when using the example CSV files for an import, you also have a nice test that the parser works correct. "

I think a roundtrip without any change should not change anything, also no quote characters etc..
