### ISSUE TITLE
encrypted PDFs cannot be displayed

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3171] opened 2017-03-30 12:49 UTC
- upload this attached PDF to OS:
http://dr-h-stamm.info/downloads/r3083021ddestamm.pdf

result: it cannot be displayed because the button to display it is missing.

But the encryption allows to view the file. So there is no reason that it cannot be displayed as well by OS when this is possible in SumatraPDF and friends.

**Comment by FinnStutzenstein** [comment] 2017-03-31 06:22
PyPDF cannot give this detailed information about pdfs. Either this is a won't fix or we need a different module here.

**Comment by donovaly** [comment] 2017-03-31 16:10
> PyPDF cannot give this detailed information about pdfs

Dear @FinnStutzenstein, could you please forward this bug report to the PyPDF developers that it can be fixed there?

many thanks in advance and regards
donovaly

**Comment by donovaly** [comment] 2017-03-31 16:14
> could you please forward this bug report

OK, I found PyPDF and did it:
mstamy2/PyPDF2/issues/341

**Comment by tsiegleauq** [comment] 2019-08-27 08:22
Cannot reproduce anymore. The document provided can be projected in OpenSlides 3

**Closed by tsiegleauq** 2019-08-27 08:22 UTC
Labels: mediafiles, pdf
