### ISSUE TITLE
staff users can set non-delegate users to suport list of a motion

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2161] opened 2016-05-21 00:10 UTC
- create a motion
- log out and login as another user
- now click in the new motion the button to support it

result: nothing happens!

This is a regression and in my opinion a blocker for the next release since this is a key feature of motions.

Btw., the opposite does also not work: try to remove your support for a motion (if e.g. the admin set you to the supporter list). Then also nothing happens.

**Comment by emanuelschuetze** [comment] 2016-05-28 15:36
I can't reproduce it. The delegate user can support and unsupport a motion without problems. The admin can see that the motion was supported by delegate user.

Maybe your browser has a problem to send the post reqeust after click the "support" button? You should debug it with a network analytic tool (e.g. open the web developer tools in firefox) and confirm that the post request is successfully sent (e.g. http://localhost:8000/rest/motions/motion/2/support/).

Assigned to @donovaly

**Comment by donovaly** [comment] 2016-05-29 20:57
OK, it it a bit different. You are right: users who are in the delegates group can support and unsupport motions. But if I add a user to the supporter's list who is not a delegate he cannot undo this. So it should not be possible for the staff users to set users to a support list that are not delegates (and who therefore don't have the right to support motions).

**Comment by normanjaeckel** [comment] 2016-05-29 22:24
Hm. This means that admins of small assemblies (who do not give access to the participants at all) have a lot of more work. They can not just add some users and then set them as supporters just to show that they support the motion.

In my opinion the permission system is to control the permissions of users who log in, not to control the workflow and legal system of an assembly. (This does not mean that we should support different configurations for different legal systems according to what normal users can do if they log in.)

**Comment by donovaly** [comment] 2016-05-29 22:33
> They can not just add some users and then set them as supporters just to show that they support the motion.

You misunderstood me. If e.g. user C (only delegate) asks user A (staff member) to add him to the support list, user A should be able to do this (and also to remove him), but if user C added himself nobody should not be allowed to change this because it was himself who did this.
I assume that the database knows who did a change. So only the person who set on the supporters list will be able to unset. So in practice if user C asks stuff member user A to set him to the list, stuff user B cannot unset this, only user A. You know how it is - too many people play dirty tricks. (Imagine user B doesn't like user A because he supports other people in the party but both have to work together nevertheless to organize the meeting... Dirty, but that's life and I can tell different stories about that.)

**Comment by normanjaeckel** [comment] 2016-05-29 22:53
At the moment we do not save which user changes entries in the database. And I even do feel that we need the described restrictions here.

**Comment by donovaly** [comment] 2016-05-29 22:57
> At the moment we do not save which user changes entries in the database.

Then this should be added.

**Comment by emanuelschuetze** [comment] 2016-05-30 05:58
We have the motion log (available for staff users only) which logs each modification (timestamp and user) of a motion. So you can get the information who has changed the motion (e.g. add/remove supporter).
I see it like @normanjaeckel: We should not regulate the admin users. The OpenSlides concept is that each admin user can do the same. Each admin should represent other admins. I don't like a new permission level between two admins. For us this is not an important use case where we should spend more time now. Sorry. But you should manage it organizational - not in OpenSlides.

I closed this issue with [won't fix].

**Closed by emanuelschuetze** 2016-05-30 05:58 UTC
Labels: motion
