### ISSUE TITLE
Discussion: Allowing state to go back

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#4367] opened 2019-02-19 09:48 UTC
Please let's discuss about #4279.

If we have a workflow that states A and B point to C then the server would now allow going from A to C and "back" zu B. This is not intended by such a workflow.

**Comment by FinnStutzenstein** [comment] 2019-02-19 10:54
Mave the "back" must be added to a next state. So A->B and B->A explicitly. Then the ui can detect these "steps back" and display them seperately. Or add a flag"allow to go a state back" to make these back-links easy to understand for a user.
Other ideas?

**Comment by normanjaeckel** [comment] 2019-02-19 13:27
How can we save the correct back link in state C? State is an abstract layer and the previous state might be A or B. Only for a concrete motion the previous state was A and not B. For another it was B.

**Comment by tsiegleauq** [comment] 2019-02-20 15:25
Instinctively, I would simply provide A as a next state of B without any special "previous state" logic.
Dynamically detecting the previous state might not be too easy if A and B simply have each other as "next states".

**Comment by FinnStutzenstein** [comment] 2019-02-28 07:59
@normanjaeckel Ah, I think I misunderstood you. You mean. A->C and B->C. Initial state is A. A user goes from A to C as intended by the workflow. Is it correct, that you just want to go "exactly" back, e.g. one button "go back" that must go from C to A, because A was selected before?

**Comment by tsiegleauq** [comment] 2019-02-28 08:32
A leads to C
B leads to C

The question is, which state is the predecessor of C?

Regardless of the initial state / under consideration of the initial state.

**Comment by FinnStutzenstein** [comment] 2019-02-28 08:40
Possible answers:

- A and B
- The state of the motion where it was previously (so A xor B)

One is history-sensitive, one not. We must decide hat we want. The first is easy to implement, but maybe one does not allow to go back to B if the statechange before was A->C.

**Comment by tsiegleauq** [comment] 2019-04-02 09:39
Since you assigned me here, I would decide for the first solution. 

> A and B

Context sensitive changes of options are most likely to confuse the user

**Comment by tsiegleauq** [comment] 2019-04-02 09:45
Apparently, it this was already implemented that way. Closing.

**Closed by tsiegleauq** 2019-04-02 09:45 UTC
Labels: needs discussion
