### ISSUE TITLE
Default Voting Type only "analog" available

### ISSUE THREAD

**Issue by Tatsu941** [OpenSlides/OpenSlides#6470] opened 2022-08-02 09:40 UTC
**Describe the bug**
Under Settings -> Elections in the "Ballots" section the "Default Voting Type" can only be chosen as "analog"

**How to Reproduce**
Follow the Steps above

**Expected behavior**
Beeing able to also choose "nominal" and "non-nominal" additonally to "analog"

**System information**

- OpenSlides-Version: [OpenSlides 3.4.1-master]
- Python Version: 2.7.18
- Device: PC
- OS: Windows 10
- Browser: Firefox v.103, Chrome v.103

**Screenshots**
Only one option:
[https://i.gyazo.com/174bda27e05832bcac0d56d74bbf664b.png](url)

**Comment by tsiegleauq** [comment] 2022-08-03 09:21
Cannot reproduce. Analog is on the top of the list where you describe it.
![image](https://user-images.githubusercontent.com/10233032/182573115-cd91fe02-83f9-4f3a-a8da-76553935cc0c.png)

**Comment by Tatsu941** [comment] 2022-08-03 10:18
I only have analog, thats the Problem. I installed it exactly as the Documentation said.

**Comment by jsangmeister** [comment] 2022-08-08 06:47
You probably don't have electronic voting enabled. In the organization settings, the superadmin must check the option "Enable electronic voting" to be able to create electronic polls.

**Comment by Tatsu941** [comment] 2022-08-08 17:10
> 

Yes! This is it. How do I login as "superadmin"? Normal admin I know but not the super admin

**Comment by jsangmeister** [comment] 2022-08-15 06:02
That depends on how you set up your instance. Normally, the initial user should also be superadmin. Did you check if can change the settings with your normal admin? Alternatively, "superadmin"/"superadmin" might work.

If not, you can use the manage tool (https://github.com/OpenSlides/openslides-manage-service) to either set the password of a user or create a new one. Hope this helps.

**Comment by jsangmeister** [comment] 2022-09-05 08:57
closing this. Feel free to open a new issue if you encounter another error.

**Closed by jsangmeister** 2022-09-05 08:57 UTC
