### ISSUE TITLE
regression: candidates of an election are no longer on the speaker's list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3022] opened 2017-02-28 23:19 UTC
- create a new election
- add some candidates
- go to the speaker's list

result: the candidates are not by default on the list. This feature was a useful one because I cannot imagine a case that candidates don't speak. Maybe a candidate is not participating, but it is much quicker to remove these few than to add all other candidates to the speaker's list.

So if this feature was removed purposely, please tell me, if not this bug is a regression.

**Comment by emanuelschuetze** [comment] 2017-03-01 08:55
This is a duplicate of #2684.

Workaround: You have to create a ballot first. Then all candidates are added to the list of speakers.

**Closed by emanuelschuetze** 2017-03-01 08:55 UTC
