### ISSUE TITLE
Watch permission changes on client side

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2851] opened 2017-01-14 09:48 UTC
If an admin change a permission the DOM tree (os-perms, ...) should update directly and show/hide elements that are connected with the permission.

Example: Delegate views an election; admin removes 'can_nominate_himself' --> 'Add me' button should disappear.

**Comment by normanjaeckel** [comment] 2017-01-18 14:43
See #1855

**Comment by emanuelschuetze** [comment] 2017-01-19 08:00
this is a duplicate of #1855, closed.

**Closed by emanuelschuetze** 2017-01-19 08:00 UTC
Labels: high
