### ISSUE TITLE
Initial logon with superadmin times out

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#6538] opened 2023-01-14 17:56 UTC
**Describe the bug**
After installation of OpenSlides as laid out in [INSTALL.md](https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md) and exposing OpenSlides via nginx, I cannot log into OpenSlides using the superadmin login.
The credentials are accepted. but the page does not load.
<details> <summary> I get a perpetually spinning wheel: </summary>

![grafik](https://user-images.githubusercontent.com/29462559/212487471-421397ea-5622-44d7-8f47-eca7db37fef1.png)

</details>

**How to Reproduce**

1. Install OpenSlides as per [INSTALL.md](https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md)

<details>
<summary> 2. Expose OpenSlides via nginx using a config like this: </summary> 

```nginx
server {

  server_name openslides.example.com;

  location / {

        proxy_pass http://localhost:8000;
        proxy_set_header   Host               $host:$server_port;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        proxy_set_header   Upgrade            $http_upgrade;
        proxy_set_header   Connection         "upgrade";

  }


    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/openslides.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/openslides.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = openslides.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  server_name openslides.example.com;


    listen 80 http2;
    return 404; # managed by Certbot


}
```
</details>

3. Try loggin into OpenSlides using `superadmin` default credentials
<details>
<summary> 4. No error message about incorrect credentials appears, but the landing page never loads, instead, the loading animation never stops </summary>

![grafik](https://user-images.githubusercontent.com/29462559/212487471-421397ea-5622-44d7-8f47-eca7db37fef1.png)

</details>

**Expected behavior**
After logging in using the default `superadmin` credentials, the landing page loads correctly.

**System information**

- OpenSlides-Version: whatever I get using `wget github.com/…releases/download/latest/openslides`
- docker-compose version 1.29.2, build unknown
- Browser: Tried Firefox, Chrome and Edge
- OS: Ubuntu 22.04.1 LTS x86_64

**Additional context**
When I stop OpenSlides using `docker-compose down` after trying to log into OpenSlides, the landing page briefly loads as the different services are shutting down. If I start OpenSlides again immediately, the session appears to continue working, I can navigate the interface, although none of my changes are saved (no error messages, though).
Reloading returns the session to the login page.
This behaviour only appears when using Chrome, not using Firefox.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29462559/212487471-421397ea-5622-44d7-8f47-eca7db37fef1.png)

**Comment by InterFelix** [comment] 2023-01-14 17:58
This issue is what @zell-mbc's efforts at #6536 ultimately resulted in as well.

**Comment by InterFelix** [comment] 2023-01-16 08:26
Adjacent to this:
I was unable to get the OpenSlides manage tool to work with any port other than 8000.
Maybe I couldn't figure out the correct syntax for `./openslides initial-data -a`, but whenever I specified a proxy-port other than 8000 (default), I couldn't get `./openslides initial-data` to work.
I tried with `-a localhost:<PORT>`, `-a "localhost:<PORT>"`, `-a 127.0.0.1:<PORT>`, `-a "127.0.0.1:<PORT>"`, `-a <PROXY_CONTAINER_IP>:<PORT>` and `-a "<PROXY_CONTAINER_IP>:<PORT>"`,
Maybe the `./openslides initial-data -a` option is just broken.

**Comment by Magolv** [comment] 2023-01-19 23:12
Hi there,
I have the exact same issue with OpenSlides as what @zell-mbc ended up with in #6536 and @InterFelix has described here.

When I take a look at the docker-compose logs, I see proxy_1 occasionally firing an error:

proxy_1             | {"level":"error","ts":1674168282.618631,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}


### Tests performed so far
**1. Using Safari and loading via nginx reverse proxy:**
proxy_1 immediately fires an error (see above)
login leaves me with a spinning wheel, landing page never loads

**2. Using Safari and loading via ssh tunneling to localhost:8000:**
login page looks different (see screenshots)
proxy_1 immediately fires an error (see above)
login leaves me with a spinning wheel, landing page never loads

**3. Using Chrome and loading via nginx reverse proxy:**
proxy_1 immediately fires an error (see above)
login leaves me with a spinning wheel, landing page never loads

**4. Using Chrome and loading via ssh tunneling to localhost:8000:**
login page looks different (see screenshots)
proxy_1 immediately fires an error (see above)
login goes through, landing page loads, changes apparently get saved to the database

### Additionally
I also was unable to get OpenSlides to work with any other port than 8000.

### Screenshots from Safari
login page via nginx reverse proxy
<img width="529" alt="Bildschirmfoto 2023-01-19 um 23 35 35" src="https://user-images.githubusercontent.com/123126736/213577953-47a5a2bb-39ff-420e-a984-a916061fb490.png">

login page via ssh tunneling to localhost:8000
<img width="490" alt="Bildschirmfoto 2023-01-19 um 23 35 46" src="https://user-images.githubusercontent.com/123126736/213578129-0cd50bb6-0d2b-46ca-a42e-d9f8f92674a0.png">

**Comment by Magolv** [comment] 2023-01-20 06:58
Hello,
I was able to solve the problem by changing the configuration of my nginx reverse proxy to:
```
location / {
	proxy_pass http://localhost:8000;
	proxy_set_header Host $http_host;
	proxy_buffering off;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto "https";
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "Upgrade";
}
```
Now the login goes through and the landing page loads.
Changes apparently get saved to the database.

### Additional Info
In my-config.yml I have set:
```
enableLocalHTTPS: false
```

I'm still trying to get it to work with any other port than 8000.

**Comment by zell-mbc** [comment] 2023-01-20 09:00
I can confirm that your nginx settings are working for me as well. Thanks a lot for helping out! 
I can't comment on the port as I am ok with the default 8000.

**Comment by InterFelix** [comment] 2023-01-20 20:20
I can confirm this as well. The only changes I made as compared to my last nginx config are:
1. changing `proxy_set_header Host $host:$port;` to `proxy_set_header Host $http_host;`
2. inserting `proxy_buffering off;`
3. changing `proxy_set_header X-Forwarded-Proto $scheme;` to `proxy_set_header X-Forwarded-Proto "https";`

The problem must lie in one of these lines.

**Comment by kljbdvpb** [comment] 2023-01-24 13:06
Is this an issue regarding the disability of nginx using http2 through proxy_pass? 

I tried to use http2_push_preload but nothing changes. Chrome and Firefox tell me that the ressources (especially login) are loaded using http1.1.

**Comment by normanjaeckel** [comment] 2023-02-01 20:44
OpenSlides is working on another port than 8000. I just tried:

Use a custom config.yml

```yml
---
port: 8001
```

Then run:

```bash
$ ./openslides --config config.yml setup .
$ docker-compose up --detach
$ ./openslides --address "localhost:8001" initial-data
```

So you have to use `port: 8001` during creation of the docker-compose.yml (or you modify the respectiv string in proxy section) AND you have to use the `--address` flag.

**Comment by kljbdvpb** [comment] 2023-02-07 12:14
Forcing nginx to use HSTS by adding this to the nginx.conf did the trick for me.

`add_header Strict-Transport-Security "max-age=63072000; includeSubdomains;";`

**Comment by res2k** [comment] 2023-03-28 23:39
After doing this:
>     2. inserting `proxy_buffering off;`
...the problems I had with things apparently timing out went away.

**Comment by jsangmeister** [comment] 2023-03-31 07:14
Closing this since it convoluts multiple issues and multiple fixes have been added now. Feel free to still add a comment if you discover a new fix or open a new issue if some other problem pops up.

**Closed by jsangmeister** 2023-03-31 07:14 UTC
Labels: bug
