### ISSUE TITLE
RuntimeError: SET_NULL_AND_AUTOUPDATE is used in an invalid usecase. Please report the bug!

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#4192] opened 2019-01-27 10:48 UTC
Create a motion. Create an "Ändernugsantrag". Now try to delete the original motion.

You get the Runtimeerror

**Comment by emanuelschuetze** [comment] 2019-01-28 20:06
I can't reproduce it with current master... Can you try again please?

**Comment by normanjaeckel** [comment] 2019-01-28 20:56
Can't reproduce too.

**Comment by FinnStutzenstein** [comment] 2019-03-04 12:42
Should be fixed with #4447 . Can you try it again?

**Comment by emanuelschuetze** [comment] 2019-03-04 14:17
> Should be fixed with #4447 

Yes, confirmed.

**Closed by emanuelschuetze** 2019-03-04 14:17 UTC
