### ISSUE TITLE
Cache does not update motion version

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3484] opened 2017-11-10 12:48 UTC
There are sometimes (couldn't be recreated yet) artifacts, that motions are displayed in the list view, but without a title, text and reason. After deleting the restricted data cache and reloading the motions are completely loaded.
It seems, that the cache is updated for a motion, but just the motion object is inserted but not the motion version object(s).

**Comment by emanuelschuetze** [comment] 2018-02-21 10:11
Can't reproduce. Moved to 2.3

**Comment by ostcar** [comment] 2018-08-09 12:41
The cache was complete rewritten with #3784 Since this can not be reproduced and it may be fixed, I would suggest, you close this issue.

**Closed** 2018-08-30 07:56 UTC
Labels: autoupdate, bug, needs info
