### ISSUE TITLE
missing translation for motion log

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2154] opened 2016-05-19 22:49 UTC
- use OpenSlides with English menus
- create a motion and edit it afterwards
- go to the motion overview and show there the log/history

result: the content of the log is in German instead of English:
![no-version-history](https://cloud.githubusercontent.com/assets/1828501/15412015/9d4de5dc-1e24-11e6-8b9f-79325fd9136b.jpg)

**Comment by emanuelschuetze** [comment] 2016-05-31 06:50
This is a duplicate of #2025. We will move the translations from server (Rest API) to client (JS).

**Closed by emanuelschuetze** 2016-05-31 06:50 UTC
