### ISSUE TITLE
Incorrect fullscreen styling

### ISSUE THREAD

**Issue by lesteenman** [OpenSlides/OpenSlides#2097] opened 2016-05-09 19:53 UTC
The current fullscreen mode (at least during file presentations) seems to not update to screen size changes, and to be incorrect on wide screens. The files will always be scaled up to fill as much of the screen rather than fit into the screen.

I fixed this in Chrome devtools to test by changing the `.fullscreen canvas` style to include `max-width: 100%;`, and by removing the fixed element style on that canvas.

**Comment by emanuelschuetze** [comment] 2016-05-10 06:56
Right, what we really want is to fit the presentation into window (with full width or height). Currently only the full width is used. That has to be fixed.

It would be great if you can create a pull request for it!

**Comment by lesteenman** [comment] 2016-05-10 09:15
I'll take a look at it once I set up a fork of the project, so we can use the fixed version ourselves next week.

**Comment by lesteenman** [comment] 2016-05-10 11:39
I do have a question regarding this: I see that all of this logic is happening in `openslides-libs.js`, which just seems one big blob of various libraries. Is it intended to work in this file, or is it generated from separate JS files? (As I can't seem to find those)

**Comment by normanjaeckel** [comment] 2016-05-10 11:44
The `openslides-libs.js` is generated by the gulp task `js-libs`. We install third party packages via bower and concat them with gulp. All of our own logic is in separate JS files in the various openslides modules (core, motion, agenda, ...).

**Comment by lesteenman** [comment] 2016-05-10 11:45
Ah, bower instead of NPM. That's why I couldn't find the packages.

**Comment by normanjaeckel** [comment] 2016-05-10 11:49
NPM is only for our dev tools like bower, gulp and gulp plugins.

**Comment by lesteenman** [comment] 2016-05-10 12:24
This seems to be an issue with angularjs-pdf, since their `page-fit` scale property does not seem to work properly (behaves like `page-fill` instead). I'll make a pull request for them.

Other than that: I also stated that window resizes do not trigger re-scaling of the PDF. Is this intended, or would a PR for that be welcome?

**Comment by lesteenman** [comment] 2016-05-10 13:17
Correction: It is intended behavior for PDF-JS, as in the general use case, it does not matter if a PDF exceeds certain height limits. We might be able to fix this ourselves from OpenSlides code (not too pretty, since it breaks encapsulation of the PDF elements), or send in a PR to angularjs-pdf to include an option to limit the height.

**Comment by emanuelschuetze** [comment] 2017-01-06 22:12
Moved from duplicate issue #2114:
"""
Summarize final suggestion to fix this issue:
By default each pdf projection should show the whole pdf document (= full width or height).
For DIN A4 page = full height (horizontal centered, with black borders left/right)
For a widescreen presentaiton = full width (vertical centered, with black borders top/bottom).
"""

@lesteenman Does your pullrequest for angularjs-pdf (https://github.com/sayanee/angularjs-pdf/pull/128) fix this suggestion? - BTW: You have to update your pr for review.

**Comment by emanuelschuetze** [comment] 2018-02-21 09:52
This issue is still valid. The last suggestion has to implement...

**Comment by lesteenman** [comment] 2018-02-21 11:06
Sorry for having left this hanging, but I haven't been using OpenSlides for a long time now, and I currently don't have any of my free time to work on this.

**Comment by emanuelschuetze** [comment] 2018-02-21 11:08
@lesteenman No problem. We keep this issue open until somebody has time to realize it.

**Comment by jsaalfeld** [comment] 2018-11-05 13:39
Issue #3148 is a duplicate of this. If this is still an issue with 3.0, please reopen Issue #3148.

**Closed by jsaalfeld** 2018-11-05 13:39 UTC
Labels: mediafiles, projector
