### ISSUE TITLE
Use .bowerrc

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1678] opened 2015-11-12 08:58 UTC
see discussion on users-de:
http://mail.openslides.org/pipermail/users-de/2015-November/000408.html

**Comment by ostcar** [comment] 2016-01-08 23:56
@normanjaeckel can you check this?

**Comment by normanjaeckel** [comment] 2016-01-09 17:04
Won't fix as discussed. The problem is in https://github.com/ck86/main-bower-files/blob/master/lib/index.js: This should be solved there.

Workaround: Use your own .bowerrc in the parent directory of OpenSlides root repo dir.

**Closed by normanjaeckel** 2016-01-09 17:04 UTC
Labels: system
