### ISSUE TITLE
Missing title "Decision"  in exported motion PDF

### ISSUE THREAD

**Issue by TheJoKlLa** [OpenSlides/OpenSlides#5364] opened 2020-05-13 04:15 UTC
**Describe the bug**
Missing title "Decision" in export PDF of motion.

**How to Reproduce**
Export Motion to PDF

**Expected behavior**
Like the reason title above the decision text.

**System information**
- OpenSlides-Version: 3.1

**Comment by tsiegleauq** [comment] 2020-05-13 11:43
Nothing to reproduce. You need to give more information about your error, what you expect and how to reproduce it. I cannot comprehend what you mean with `decision title` and `reason title`.

The issue template exists for a reason. Stick to it. Tell exactly what you do, how you are doing it, and give an output example.

![image](https://user-images.githubusercontent.com/10233032/81808161-96845080-951f-11ea-9efe-7afdcc0dadaa.png)

**Comment by TheJoKlLa** [comment] 2020-05-17 22:19
![title](https://user-images.githubusercontent.com/25747734/82161460-2cf89f00-989d-11ea-86ee-9577dafe4116.png)

**Comment by tsiegleauq** [comment] 2020-05-17 22:54
You are still not making clear what the problem is. The title, "Decision", is obviously there.

**Comment by tsiegleauq** [comment] 2020-05-19 11:07
I suppose what you are trying to express is that you want the word "Decision" above "The assembly may decide" in both the HTML and PDF view.

Logically spoken, the text of a motion is not a "decision" it's a "proposal". If you want to have decision instead of "the assembly may decide" use custom translations

**Comment by tsiegleauq** [comment] 2020-05-19 11:07
furthermore, this is of course not an issue or a bug, but a feature request.

**Comment by emanuelschuetze** [comment] 2020-05-19 11:20
> Logically spoken, the text of a motion is not a "decision" it's a "proposal". If you want to have 
> decision instead of "the assembly may decide" use custom translations

Indeed. The descision of a motion is the state (e.g. "accepted"). The motion text is not the descision. If you like you can use the preamble ("The assembly may decide...") which can be custimized in motion settings.

-> No feature request. I'll close it here.

**Closed by emanuelschuetze** 2020-05-19 11:20 UTC
Labels: easy, feature, low, needs discussion
