### ISSUE TITLE
Agenda autoupdate problem

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1891] opened 2016-01-25 14:35 UTC
- Add two new items: a hidden and a visible one.
- Move the visilble item below the hidden one so that it becomes a child.
- Now the visible one is shown as hidden, which is correct and expected.
- Now QuickEdit the parent item and make it visible -> It is expected that all items are now marked as visible, but the second one itn't. Only reload helps.

**Comment by emanuelschuetze** [comment] 2016-01-25 22:17
@ostcar Any idea how we can trigger the auto update for all child items if item.type is changed?

**Comment by ostcar** [comment] 2016-01-27 16:38
There is another way to reproduce this error:

Create two normal items and one hidden items.
Make one normal item the child of the other normal item.
Then make the normal parent item a child of the hidden item

**Comment by ostcar** [comment] 2016-01-27 16:47
The problem is, that is_hidden is part of the rest api and is not calculated on the client.

If on a parent item the is_hidden flag changes then only the parent item is send to the client and therefore the child is not updated.

The solution is to create a method on the client then checks the flag from the rest api and also the flag on any parent element. Therefore the rest-api should be changed to return the value from the db and not the calculated value (because it has to be calculated on the client anyway).

@normanjaeckel could you change the server and @emanuelschuetze could you change the client?

**Comment by normanjaeckel** [comment] 2016-01-27 19:20
@emanuelschuetze can fix the server and client in one step: For the server only remove `'is_hidden'` from `fields` in agenda/serializers.py ItemSerializer meta class.

**Comment by jsaalfeld** [comment] 2018-11-05 13:40
This should be solved with the new client. If otherwise, please reopen this issue.

**Comment by normanjaeckel** [comment] 2018-11-09 21:31
I think this is still valid.

**Comment by tsiegleauq** [comment] 2019-08-23 14:21
Cannot be reproduced anymore. Closing.

**Closed by tsiegleauq** 2019-08-23 14:21 UTC
Labels: agenda, autoupdate, bug, server
