### ISSUE TITLE
Deleting related lines for amendments will cause errors in 'line-numbering.service'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#4954] opened 2019-08-27 13:42 UTC
**Describe the bug**
If for a motion an amendment exists and the lines, which has "change-requests", are deleted, the `line-numbering.service` can't find the lines. See picture below for details...

**How to Reproduce**

1. Go to a motion and create an amendment.
2. Click on 'Edit' in the same motion.
3. Delete the lines, previously selected for the amendment.
4. See error in the console and the amendment-list for this motion.

**Expected behavior**
There could be some different behaviours:
- Either the motion cannot be edited anymore, if at least an amendment exists
- Or the amendment should be deleted, since it is redundant. 

**System information**

- OpenSlides-Version: Latest
- Python Version: 3.7
- Device: Notebook
- OS: Arch Manjaro
- Browser: Chrome
- Browser-Version: 76

**Screenshots**
![error_in_motion_and_amendment](https://user-images.githubusercontent.com/10206688/63776124-0a72c000-c8e1-11e9-8b16-7d49a8882ece.png)

**Comment by tsiegleauq** [comment] 2019-12-09 16:05
cannot reproduce anymore. Might be fixed tho.

**Comment by tsiegleauq** [comment] 2020-06-22 08:52
No updates, cannot reproduce, no complains so far. Closing.

**Closed by tsiegleauq** 2020-06-22 08:52 UTC
Labels: bug
