### ISSUE TITLE
Voting tool stopped working after update from 3.1 to 3.2

### ISSUE THREAD

**Issue by max-stebens** [OpenSlides/OpenSlides#5484] opened 2020-07-24 13:01 UTC
Dear Openslides community,
We faced an issue a few days ago after upgrading to version 3.2
Unfortunately, while creating new votes, we get the following error message: **Error: The requested method is not allowed. Please contact your system administrator.**

Unfortunately, we don´t know exactly if it worked fine before upgrading to the new version. We did never test, but now we need to setup a vote quickly, and it is not possible...

Is this already a known issue, or is there something we can try to make things work again?

Thanks in advance,
Max

**Comment by tsiegleauq** [comment] 2020-07-24 13:21
As far as I know voting works fine on both OpenSlides 3.2 release and master. Voting did not really exist in OpenSlides 3.1. Are you, by any chance, using one of the deprecated voting plugins (i.e https://github.com/OpenSlides/openslides-voting)

Usually when a request goes wrong your browsers JavaScript console shows more accurate errors than the snackbar in OpenSlides. Furthermore, your browsers network tab might indicate where the requests are going. Perhaps you send your requests to a route that does not exist anymore?

In any case, if you have been using 3.1 before and are migrating to 3.2, you need to clean your browser cache completely and migrate the existing database using `python manage.py migrate`

Please stick to the issue template to give me a chance to reproduce your errors:
**Describe the bug**
A clear and concise description of what the bug is.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**System information**

- OpenSlides-Version: [e.g. 2.1, 2.2, 2.3, 3,0]
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: [e.g. 3,5, 3.6, 3.7]
- Device: [e.g. iPhone6, Notebook]
- OS: [e.g. Andoird 7, iOS8.1, Windows 10]
- Browser: [e.g. chrome, firefox, opera, edge, safari]
- Browser-Version: [e.g. 22]

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by tsiegleauq** [comment] 2020-07-28 08:39
not a bug, not meeting the issue criteria. closing until further information was provided

**Closed by tsiegleauq** 2020-07-28 08:39 UTC
Labels: bug, needs info, voting
