### ISSUE TITLE
npm test produces *sometimes* an error while loading LoginPrivacyPolicyComponent

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3982] opened 2018-11-05 11:30 UTC
The following error appears sometimes in travis and even on a local machine. This should be fixed, so the build is reliable.

```
HttpErrorResponse{headers: HttpHeaders{normalizedNames: Map{}, lazyUpdate: null, headers: Map{}}, status: 0, statusText: 'Unknown Error', url: null, ok: false, name: 'HttpErrorResponse', message: 'Http failure response for (unknown url): 0 Unknown Error', error: ProgressEvent{isTrusted: true}}
Chrome 70.0.3538 (Linux 0.0.0): Executed 46 of 216 SUCCESS (0 secs / 17.17 secs)
ERROR: HttpErrorResponse{headers: HttpHeaders{normalizedNames: Map{}, lazyUpdate: null, headers: Map{}}, status: 0, statusText: 'Unknown Error', url: null, ok: false, name: 'HttpErrorResponse', message: 'Http failure response for (unknown url): 0 Unknown Error', error: ProgressEvent{isTrusted: true}}
e 70.0.3538 (Linux 0.0.0): Executed 47 of 216 SUCCESS (0 secs / 17.801 secs)
Chrome 70.0.3538 (Linux 0.0.0) LoginPrivacyPolicyComponent should create FAILED
	[object ErrorEvent] thrown
Chrome 70.0.3538 (Linux 0.0.0): Executed 48 of 216 (1 FAILED) (0 secs / 18.322 secs)
Chrome 70.0.3538 (Linux 0.0.0) LoginPrivacyPolicyComponent should create FAILED
	[object ErrorEvent] thrown
e 70.0.3538 (Linux 0.0.0): Executed 49 of 216 (1 FAILED) (0 secs / 18.847 secs)
e 70.0.3538 (Linux 0.0.0): Executed 50 of 216 (1 FAILED) (0 secs / 18.85 secs)
'The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.'
Chrome 70.0.3538 (Linux 0.0.0): Executed 50 of 216 (1 FAILED) (0 secs / 18.85 secs)
WARN: 'The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.'
e 70.0.3538 (Linux 0.0.0): Executed 51 of 216 (1 FAILED) (0 secs / 19.468 secs)
```

**Comment by tsiegleauq** [comment] 2018-11-08 07:50
Have not been able to reproduce that so far.

**Comment by tsiegleauq** [comment] 2019-08-30 11:42
Still not able to reproduce. Closing.

**Closed by tsiegleauq** 2019-08-30 11:42 UTC
Labels: client, tests
