### ISSUE TITLE
TypeError: Cannot read property 'groups_id' of null

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2596] opened 2016-11-08 08:17 UTC
Reloading the groups list view gets JS error:`TypeError: Cannot read property 'groups_id' of null`

**Comment by FinnStutzenstein** [comment] 2016-11-08 09:13
@emanuelschuetze Duplicate of #2588 .

**Closed** 2016-11-08 09:20 UTC
Labels: bug, js, users
