### ISSUE TITLE
OS 2.1: regression: cannot display motions

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2614] opened 2016-11-10 22:43 UTC
With yesterday's master (version sent me by Emanuel) I can no longer display motions. To reproduce

- display the agenda
- change to the motions, open a motion and display it
- undisplay the motion and press again display

result: now the projector is empty (except of the clock) and I get these error messages:

2016-11-10 23:39:36,727 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_projector:
Traceback (most recent call last):
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\worker.py", line 120, in run consumer(message, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\sessions.py", line 180, in inner result = func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\auth.py", line 73, in inner return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\sessions.py", line 64, in inner return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\auth.py", line 89, in inner return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\autoupdate.py", line 81, in ws_add_projector
    output.append(required_collection_element.as_autoupdate_for_projector())
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\collection.py", line 127, in as_autoupdate_for_projector  'get_projector_data')
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\collection.py", line 104, in as_autoupdate
    *args)
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\motions\access_permissions.py", line 53, in get_projector_data data['comments'][i] = None
TypeError: 'NoneType' object does not support item assignment
[2016/11/10 23:39:36] HTTP GET /static/i18n/openslides_votecollector/de.json/ 200 [0.11, 127.0.0.1:52514]

**Comment by emanuelschuetze** [comment] 2016-11-11 08:57
I can't reproduce it.
@normanjaeckel Maybe you have any idea what could faild by looking at the traceback? It stops here...
```
motions\access_permissions.py", line 53, in get_projector_data data['comments'][i] = None
TypeError: 'NoneType' object does not support item assignment
```
@donovaly Can you try to reproduce it with a fresh database and a step-by-step instruction?

**Comment by donovaly** [comment] 2016-11-12 01:45
> Can you try to reproduce it with a fresh database

I deleted now everything in the folder "openslides". After restarting OS, the bug is gone.

BUT I assume that users of OS 2.0 want to use existing databases also in OS 2.1.
I therefore deleted again everything in the folder "openslides" and then only copied into the folder "openslides" a test database once created with OS 2.0 (that I already used to try out and document OS 2.1). 
This is the used database:
[db.zip](https://github.com/OpenSlides/OpenSlides/files/586993/db.zip)
After starting OS the bug reappears with a slightly different traceback than in my initial comment: 

Traceback (most recent call last):
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\worker.py", line 120, in run
    consumer(message, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\autoupdate.py", line 129, in send_data
    output.append(element.as_autoupdate_for_projector())
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\collection.py", line 127, in as_autoupdate_for_projector
    'get_projector_data')
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\collection.py", line 104, in as_autoupdate
    *args)
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\motions\access_permissions.py", line 53, in get_projector_data
    data['comments'][i] = None
TypeError: 'NoneType' object does not support item assignment

**Comment by emanuelschuetze** [comment] 2016-11-15 20:01
@donovaly Should be fixed now in current master. Please retest it with your old database. Thanks!

**Closed** 2016-11-15 20:01 UTC
Labels: high, motions

**Comment by donovaly** [comment] 2016-11-19 13:41
Confirmed fixed
