### ISSUE TITLE
motion text line numbering is incorrect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3027] opened 2017-03-01 23:13 UTC
- create a new motion (assure that you have set in the OS settings to number outside)
- now enable inline editing and add a word
- make the text color of the inserted text green
- strike through the word before the inserted one and make it read.
- save the change

result: the line numbers are destroyed: instead of 1 and 2 there are now 4 line numbers overlapping each other:
![localhost 8000 2017-03-02 00-11-30](https://cloud.githubusercontent.com/assets/1828501/23485697/d7cf1746-fedc-11e6-8ff7-55b391afbb75.jpg)

Now one might highlight a line. As you can see there are now 4 lines to be highlighted although just a word was inserted (no line break or paragraph break)

**Comment by emanuelschuetze** [comment] 2017-03-03 15:41
Confirmed with current master.  An easier way to reproduce:

* Create new motion with some dummy text.
* Edit motion (in dialog or inline mode): strike through one word in the first line.
* Save
=> Line numbering for first line is broken (shows overlapping numbers: 1/2/3), second line starts with 4.

@CatoTH Please look at this issue.

**Comment by CatoTH** [comment] 2017-03-04 15:22
The problem was the unknown STRIKE-Tag. This should be fixed by https://github.com/OpenSlides/OpenSlides/pull/3044 .

Anyway, it might be considerable to adjust CKEditor to use CSS-Styles to achieve the same result instead of relying on STRIKE, as this tag seems to be deprecated since HTML4, let alone HTML5 (https://developer.mozilla.org/de/docs/Web/HTML/Element/strike).

**Closed** 2017-03-05 19:23 UTC
Labels: motions

**Comment by donovaly** [comment] 2017-03-06 22:29
Confirmed fixed. Many thanks.
