### ISSUE TITLE
Rename `person` to `user` in MotionSubmitter and MotionSupporter models.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1428] opened 2015-01-24 19:03 UTC
The field to the user should be renamed to `user`. At the moment it is person. Don't forget to rename serializer fields (if existing).

**Comment by ostcar** [comment] 2015-01-24 23:11
This is a duplicate of #1348

**Closed** 2015-09-04 21:59 UTC
Labels: clean up, motion
