### ISSUE TITLE
Start time field of countdowns allows invalid times

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2125] opened 2016-05-14 00:27 UTC
one can insert there everything and not only times. For example one might accidentally insert "5;90" or "r:90". The result is an invalid time and one might wonder what is going on (in this case why the countdown is only 5 seconds long or why it starts at 0:00 and then to negative time).

The solution is to allow only times, if possible a dialog pops up where one can set the time via combo boxes. (I mean a dialog like the one one gets when setting the colors in the settings of OpenSlides.)

**Comment by emanuelschuetze** [comment] 2016-05-28 16:02
I can confirm the invalid input behaviour:
* If you enter a invalid (no integer) time (e.g. r:90) the countdown is set to "0:00". It's not wrong but maybe in this case it would be better to keep the old value.
* If you enter a wrong separator (e.g. 5;10) the countdown is set to "0:05" (cuts the last part). That should be changed to "5:10". So every separator between two integer values should assumed as ":" character.

Do you really sure that a popup dialog with combo boxes for minutes and seconds are the best solution? Could be very inconvenient to select the fields by mouse. And how long should the minutes field be? Currently you could also enter e.g. 720 min for 12h. A combo box (select box) is not really good for unlimited values... I dont like a popup dialog for countdowns. 
 
Maybe you can help to suggest concrete improvements for the error handling? Please make some examples with expected solutions.

_Assigned to @donovaly _

**Comment by donovaly** [comment] 2016-05-29 21:21
> Do you really sure that a popup dialog with combo boxes for minutes and seconds are the best solution?

Yes.

> Could be very inconvenient to select the fields by mouse. And how long should the minutes field be?

OK, no combo box, but it is quite simple:
- a dialog pops up that contains 2 text input fields (in the space between the 2 fields is a ':' character)
- the text fields only accept the input of numbers
- the second field (for seconds) is evaluated so that 59 is the maximal number. if one enters there "99" the field background color changes to red. If the user does not change the value the 99 will automatically be reset to "59" when closing the dialog
- the first field accepts 3 digits (999 minutes) - except of Fidel Castro nobody will be able to speak for more than 3 hours at a conference ;-)

> I dont like a popup dialog for countdowns.

Why not? Everything should be as safe as possible and if I run into this bug several times and my colleague too other users will for sure run into this sooner or later.

**Comment by donovaly** [comment] 2016-11-01 17:23
Still in OS 2.1dev. This bug could also be postponed to 2.2. It would be valuable since typos appear often but it should not extend the time until 2.1 is released.

**Comment by FinnStutzenstein** [comment] 2017-04-13 08:55
@donovaly Can you check this again? We have made some developments for this; maybe this can be closed.

**Comment by donovaly** [comment] 2017-04-23 23:53
This is still an issue. Exactly as i wrote in my initial comment:

"one might accidentally insert "5;90" ... one might wonder what is going on (... why it starts at 0:00 and then to negative time)."

**Comment by emanuelschuetze** [comment] 2017-04-24 07:19
> "one might accidentally insert "5;90" ... one might wonder what is going on (... why it starts at 0:00 
> and then to negative time)."

I can confirm it: Entering `5;90` goes to `0:00`. That's correct because it is an invalid time input. So its not a bug. Yes, we could make it more tolerant and interpret each separator as `:`. Or we could keep the old time. But I think this is not really required (we should work on more important issues). So I will close this for now. Sorry.

**Comment by donovaly** [comment] 2017-04-24 12:03
> Entering 5;90 goes to 0:00. 

But this is the bug! The bug is that OS allows you to enter invalid times. The solution would be that if the user does not enter a string in the form n:nn or nn:nn (where n is a number 0-9) the input is not accepted.

**Comment by normanjaeckel** [comment] 2017-04-24 12:09
I also think we should validate the input so that the user con not accidently enter an invalid time.

**Comment by jsaalfeld** [comment] 2018-11-05 13:31
This issue will be fixed with the OS3 client. If not, please reopen this issue.

**Closed by jsaalfeld** 2018-11-05 13:31 UTC
Labels: bug, confirmed, projector
