### ISSUE TITLE
Motion PDF Change Recommendation: DEL tags surrounding multiple lines cause PDF issues

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3229] opened 2017-04-28 12:15 UTC
Hard to describe.
When you "change reco del" a whole paragraph and add some other lines, both the web view and the PDF view behaves strange:
* Web view stops to produce line numbers and starts again later with a wrong number
* PDF seems to somehow reset the rendering and starts rendering a little bit more on the right
(probably cause of [this pull request](https://github.com/OpenSlides/OpenSlides/pull/3211) )

I'll just show it:
Web View:
![bildschirmfoto von 2017-04-28 14-14-11](https://cloud.githubusercontent.com/assets/10233032/25528238/0ea6c0c6-2c1d-11e7-82f9-b238880a254d.png)

PDF View:
![bildschirmfoto von 2017-04-28 14-13-54](https://cloud.githubusercontent.com/assets/10233032/25528246/13f8484c-2c1d-11e7-82e3-2b33ce3aa6e0.png)

PDF in here is kindof dependant that the HTML code is correct.
(The coloring issue visible in here is rather implicit and probably not a topic here)

**Comment by emanuelschuetze** [comment] 2017-04-28 12:36
@FinnStutzenstein Maybe you can try a fix for this issue.

**Comment by FinnStutzenstein** [comment] 2017-05-03 06:43
This also happens, if I use replacement or insertion.

We should split this up:
First @CatoTH should look at the diffService, because already [this line](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L777) produces not expected html.
Second, if this is fixed, we can work on the pdf.

**Comment by CatoTH** [comment] 2017-05-07 18:12
@tsiegleauq Could you maybe send me the sqlite-database file, or the html of the motion and the change recommendation? Right now, I couldn't reproduce it an once, so maybe some not supported tags are used or some other edge case? The file should help figuring that out.

**Comment by tsiegleauq** [comment] 2017-05-10 12:30
yep thats hard to reproduce. I send it via email.

**Comment by emanuelschuetze** [comment] 2017-05-16 10:22
Successfully tested the fix of @CatoTH. Pull request #3254 created.

**Closed** 2017-05-16 12:25 UTC
Labels: bug, motions, pdf
