### ISSUE TITLE
Docker OpenSlides Caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF - After Stop or Reboot Container Proxy

### ISSUE THREAD

**Issue by maltsero** [OpenSlides/OpenSlides#6077] opened 2021-05-25 14:45 UTC
**Describe the bug**
After build with ./build.sh all and install certs and create the docker-compose.yml and do a docker-compose up the Proxy first started well, after a reboot or stop the container stuck and does not boot. EOF in Caddyfile! 
Caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF

**How to Reproduce**
1. OS System: Debian Buster 10
2. Install docker with docker-compose
3. Clone https://github.com/OpenSlides/OpenSlides.git --recurse-submodules
4. cd docker & ./build.sh all ( Follow the instructions in the Readme.rst )
5. docker-compose up -> it works only the first time (creating a new Container) After a stop or reboot it got an EOF in Caddyfile
6. docker-compose stop
7. doker-compose start
7. docker-compose ps
9. Proxy Container (EXIT) with current log:  Error during parsing: Unexpected EOF - After Stop or Reboot Container Proxy

**Expected behavior**
A clear working reboot or stop of OpenSlides with the Proxy Container (Caddy based) in docker-compose with:
restart: always 

**System information**

- OpenSlides-Version: 3.3
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: Docker Set-Up 
- OS: Debian Buster 10
- Browser: /
- Browser-Version: /

**Additional context**
Add any other information to comprehend your problem

**Screenshots**

**Comment by emanuelschuetze** [comment] 2021-05-27 19:16
looks like duplicate of #6071

**Closed by emanuelschuetze** 2021-05-27 19:16 UTC
Labels: bug
