### ISSUE TITLE
Group view needs options request

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3302] opened 2017-06-16 14:38 UTC
Open the group permission view (matrix). A `HTTP OPTIONS /rest/users/group/` is send each time to server. Try to remove this request. Everything should loaded on startup.

**Comment by FinnStutzenstein** [comment] 2017-06-21 12:26
duplicate of #2862 .

**Closed by FinnStutzenstein** 2017-06-21 12:26 UTC
Labels: core, users
