### ISSUE TITLE
support for arm architecture

### ISSUE THREAD

**Issue by mahehro** [OpenSlides/OpenSlides#6754] opened 2024-03-12 23:41 UTC
**Is your feature request related to a problem? Please describe.**
architecture support for arm systems is unfortunately missing. 
 
**Describe the solution you'd like**
support for arm-cpus

**Comment by jsangmeister** [comment] 2024-03-13 07:47
Duplicate of https://github.com/OpenSlides/OpenSlides/issues/6718 - there are instructions as well on how to manually set up such an instance.

**Closed by jsangmeister** 2024-03-13 07:47 UTC
Labels: feature
