### ISSUE TITLE
Selection of paragraphs does not work when amending amendments

### ISSUE THREAD

**Issue by prggz** [OpenSlides/OpenSlides#5171] opened 2020-01-08 09:46 UTC
**Describe the bug**
If you enable amendments to amendments and amending paragraphs, once you click on add amendment on an amendment, the selecting paragraph view remains empty. (see screenshot)

**How to Reproduce**
Go to settings, motions.
activate amendments
show amendments together with motions
create amendments paragraph-based, diff-enabled,
activate "amendments can change multiple paragraphs" (seems not to be necessary, but bug still occurs)
activate "allow amendments of amendments"

create motion and amendment

open amendment, click on new amendment

**Expected behavior**
Allow paragraph selection. Ideally of entire motion (as amendments to amendments may change different sections, too).

**System information**

- OpenSlides-Version: 3.1
- Python Version: [e.g. 3,5, 3.6, 3.7]
- Device: ThinkPad L540
- OS: Windows 10 Pro, 17763 using WSL Debian Buster
- Browser: firefox
- Browser-Version: 71.0

**Screenshots**
![Screenshot (25)](https://user-images.githubusercontent.com/8375100/71967787-b9ae9480-31fb-11ea-83ec-1aae88529f75.png)

**Comment by tsiegleauq** [comment] 2020-01-09 11:16
Confirmed. Also happens on current master. Very good issue report btw.

@emanuelschuetze Since 3.2 should happen soon, I'll rate this Issue as high.

**Comment by tsiegleauq** [comment] 2020-01-09 11:55
There are several ways on how to handle this issue.
Usually, it seems that people, who want to have amendments to amendments are using free text fields.

What I *would* implement is a modified "takeover" of the currently selected amendment.

Meaning, a new amendment to paragraph based amendment would bring you to a "Amendment Create" form, with the _currently altered text as description_

![image](https://user-images.githubusercontent.com/10233032/72065533-c0620800-32de-11ea-921c-7f80df7ae332.png)

would bring you to

![image](https://user-images.githubusercontent.com/10233032/72065548-c657e900-32de-11ea-9c11-f53489402657.png)

The result would then be a new amendment to the parent motion (I suppose)

@prggz any thought on that?

**Comment by tsiegleauq** [comment] 2020-01-09 16:03
What I now came up with was the following. With the PR I made we can achieve the following:
Paragraph based amendments to other paragraph based amendments will be new (pb) amendments to the main motion, but the paragraphs selected will have the information of the amendment they were created with.

To give an example:

That being my main motion:
![image](https://user-images.githubusercontent.com/10233032/72082946-4e4eea80-3301-11ea-9f84-185cf675e549.png)

This being the "normal" PB-Amendment:
![image](https://user-images.githubusercontent.com/10233032/72083133-95d57680-3301-11ea-860a-7324b201cd60.png)

Clicking "new Amendment" will give you the following: (notice that the information from the amendment are already in the paragraphs)
![image](https://user-images.githubusercontent.com/10233032/72083185-aa197380-3301-11ea-8a27-1f664420a2d3.png)

Changes and saves will then have the following result: (notice that the changes target the main motion rather than the amendment - the reason for that is that accepted amendments wont necessary reflect dependent amendments which are also likely to change)
![image](https://user-images.githubusercontent.com/10233032/72083270-cd442300-3301-11ea-9baf-6a500ed2f163.png)

**Comment by prggz** [comment] 2020-01-09 16:40
Hi Sean,

Thank you for being so quick. This wasn't anticipated, wow! 

I like your solution and I think this will be helpful, but as you asked for comment, here it is:

I'm not 100% sure how the system works internally and what's possible and what isn't so I cannot really comment on whether it's better to have an amendment to the amendment or an amendment to the motion from the technical standpoint...

The point at which I stumbled across the bug is when I thought of how to reflect the usecase of having discussed (perhaps conflicting) amendments against the original motion and coming up with a compromise (we call it in German "modifizierte Uebernahme"). I would have entered this as an accepted amendment to the amendment - as in case of someone having objections later, the original text needs to be available and restored (hence editing the amendment is just not an option).

I think having this against the original motion is not really an issue though because one could set a custom state in the other amendment with gray colour and putting a green state in the modified version. I only wonder whether it could become increasingly messy, if there are already many amendments...

In any case, would it be possible to have a link to the amendment?

What do you think?

**Comment by prggz** [comment] 2020-01-13 08:42
@tsiegelauq I pulled your PR and checked the behaviour! Thanks for your work, this seems to be working.

From the user POV I would like to raise the following points

- it would be cool if (as stated above) there was some form of reference (if it was just autosuggested as the title) to the original amendment.
- in the paragraph selection (and perhaps the edititing tool): is it possible to keep the red/green markings. It can be difficult to "find" the appropriate section otherwise...

**Comment by tsiegleauq** [comment] 2020-01-13 09:32
Hi. I was sick on Friday, hence the late reply.
Thanks a lot for your effort!

> it would be cool if (as stated above) there was some form of reference

Yes that would be cool, hence for the time being, I would recommend to set the reference to the other amendment manually using the "state extension field" (can be enabled over the workflow editor).
This feature would require to change server fields, which we try to avoid before OpenSlides 4.

> in the paragraph selection (and perhaps the edititing tool): is it possible to keep the red/green markings. It can be difficult to "find" the appropriate section otherwise...

For the editor, that would not work. as far as I know, the red and green markings rely heavily on line numbers, which are (currently) lost in the paragraph selection. I might give it a try.

**Comment by prggz** [comment] 2020-01-13 10:38
Hi, no worries.

Okay, sure, the solution you offered ("state extension field") is exactly what I thought of using :).

Slightly off-topic: I am currently hacking a state display into the projected slide - I needed a server side change (projector.py) here too. Have you been working on this anyways or would it be interesting for you if I created a PR at some point. Obviously, in that case someone would need to implement settings options to display/not to display etc. too.

Regarding the editor: That's ok. I think, if the colour is in the paragraph selection that would already be helpful!

**Comment by tsiegleauq** [comment] 2020-01-13 11:01
You can always feel free to submit a PR. While doing so, please add yourself to the [AUTHORS](https://github.com/OpenSlides/OpenSlides/blob/master/AUTHORS) file.

This use case seems to be quite unique. Usually, showing the recommendation seemed to be sufficient. However, if there is a config variable it wont hurt anybody (requires a migration file. 

ping @emanuelschuetze

**Comment by tsiegleauq** [comment] 2020-01-23 12:10
closed via #5173

**Closed by tsiegleauq** 2020-01-23 12:10 UTC
Labels: bug, confirmed, high, motions, needs discussion
