### ISSUE TITLE
regression: text line highlighting is no longer persistent

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3153] opened 2017-03-26 22:45 UTC
- highlight a line of a motion text
- go to another browser tab
- go back to the browser tab of OS

result: the highlighting is lost.

This was not the case in previous beta releases so maybe its a feature and not a bug.

**Comment by donovaly** [comment] 2017-03-26 22:49
It is a bug and a severe one that should be fixed for 2.1 because the highlighting disappears randomly:

- highlight e.g. the second line
- move the mouse a bit -> after a few seconds the highlighting is lost

So in effect the highlighting feature is useless.

**Comment by emanuelschuetze** [comment] 2017-03-27 08:22
Sorry, this is not a bug - this is a feature! :-)
If you enter a line number in "go to" field OpenSlides scrolls to this line and hightlighted this line for 3 seconds. Then the hightlighting is gone (for further read/work on the text). Otherwise we have to add a "remove highlighting" feature. 
The aim of the highlighting feature is to show quickly the desired line but don't disturb user on further work...

=> won't fix

**Closed by emanuelschuetze** 2017-03-27 08:22 UTC

**Comment by donovaly** [comment] 2017-03-27 09:19
> this is a feature! :-)

Then we have a fundamental misunderstanding. From the perspective of an assembly manager, I want to have a feature where I can highlight a motion text line (or maybe even a paragraph) and show this highlighting also in the projector. In my case of a political party, people often discuss about a certain line or paragraph and people who come e.g. back from the toilet don't know what text part the participants are currently discussing about.

As I see now the current highlight feature is not designed for that. Please tell me about the plans. In any case I will have to change the docs according to your description of the feature because as it is, I described it in the way I understood it. Is it OK to change the docs this late evening?

**Comment by emanuelschuetze** [comment] 2017-03-27 09:42
Yes please change the docs in your current pr today. I'll merge it tomorrow.

**Comment by donovaly** [comment] 2017-03-28 08:31
I changed the docs as promised and pushed a new pull request.
