### ISSUE TITLE
Assignment poll autoupdate fails

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1847] opened 2016-01-13 14:41 UTC
Create a new assignment poll, insert some votes, then publish the poll.
All correct here but now if you hide the poll again it does not disappear on normal users display. See also #1838.

**Comment by ostcar** [comment] 2016-01-13 17:46
This is a design decision.

The client looses no information that it already has. The reason is, that the angular client should be the "fried" of the user. If the user uses the rest api manually, he would also now the vote results when they where published and unpublished later.

So I would prefer to close this issue as wont fix.

**Comment by normanjaeckel** [comment] 2016-01-13 20:44
Hm. The problem is that if the manager clicks on the publish button by accident, all users get this data and the interface does not show that these data are somethink like "invalid" later. @emanuelschuetze What do you think?

**Comment by ostcar** [comment] 2016-01-15 12:30
I think we have to change this "design" decision to solve cases where parts of a rest-element where deleted

**Comment by emanuelschuetze** [comment] 2016-01-21 18:57
Looks like this issues is a duplicate of #1859 where @ostcar referenced to a js-data issue. so closed this one here.

**Closed by emanuelschuetze** 2016-01-21 18:57 UTC
Labels: assignment
