### ISSUE TITLE
TypeError while generating motion catalog pdf

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2442] opened 2016-09-27 09:23 UTC
Import some motions (e.g. from motion-demo.csv file).
Try to create motion catalog pdf.
=> Fails with JS error: `TypeError: Cannot read property 'text' of undefined`

**Comment by tsiegleauq** [comment] 2016-09-27 12:28
I can not even reproduce this.
I cannot successfully import the Motions from the OpenSlides online demo or the CSV-Exmaple-File provided during the import process itself. I make an [issue for the importing errors](https://github.com/OpenSlides/OpenSlides/issues/2447).

I can, however, elaborate a little further on the error you experience.

> TypeError: Cannot read property 'text' of undefined

During PDF generation, this can happen in 2 places and the reason for both is malformed HTML. What this actually means (or should mean) is that you try to convert a node called 'text' into a HTML document.

This can fail when the ParseHtml-moethod is called:

```
ParseHtml = function(converted, htmlText) {
    var html = HTMLValidizer.validize(htmlText);
    html = $(html.replace(/\t/g, "").replace(/\n/g, ""));
    var emptyParagraph = create("text");
    slice(html).forEach(function(element) {
        ParseElement(converted, element);
    });
},
```

or when the content is searched for image-tags:

```
angular.forEach($scope.motionsFiltered, function (motion) {
    motionContentProviderArray.push(MotionContentProvider.createInstance(converter, motion, $scope, User, $http));
});
```
and
```
var image_sources = map($(content).find("img"), function(element) {
    return element.getAttribute("src");
});
```

In both cases I already use the recently implemented HTMLValidizer-factory. This new "property 'text' of undefined" should not exist, since the factory will convert it to `<p>text</p>` if it is malformed HTML.
Probably just a special case I did not notice before.
But I cannot solve this issue as long as I cannot reproduce it.

**Comment by FinnStutzenstein** [comment] 2016-09-27 13:29
@tsiegleauq this is an well known issue: little fix for this:
Edit .venv/lib/python3.4/site-packages/channels/management/comments/runserver.py:
Change line 68 to ...range(1)...

We are waiting for an official fix from channels, but until the fix, this is the way to go to limit the workers.

There is somewhere an open issue..

**Comment by tsiegleauq** [comment] 2016-09-28 12:16
Worked for me. Thanks.

The issue happens on and "Bildungspolitik 1 (HTML)" and "Satzungsänderung § 2 Abs. 3"
The reason why this fails is pretty simple: as I expected, they both got an extremely inconvenient content, shown in the following screenshot, on the right side highlighted in blue.

![bildschirmfoto von 2016-09-28 14-07-04](https://cloud.githubusercontent.com/assets/10233032/18912875/0d3387cc-8585-11e6-9f04-5b39c1cd2d7d.png)

The motion text starts with `"""`, continiued by `<p>` Tags as usual. This is an extremely weird case of invalid HTML that currently gets interpreted as valid.

@emanuelschuetze @normanjaeckel : are you SURE that this is how html-motions should look like? I got the feeling like there is also another hidden issue.
![bildschirmfoto von 2016-09-28 14-15-52](https://cloud.githubusercontent.com/assets/10233032/18913074/1cff5ee6-8586-11e6-885d-39050f166011.png)

and if the window is smaller:

![bildschirmfoto von 2016-09-28 14-15-01](https://cloud.githubusercontent.com/assets/10233032/18913055/f9ff6a4e-8585-11e6-9a84-e76520b62552.png)

**Comment by FinnStutzenstein** [comment] 2016-09-28 12:44
@tsiegleauq Just fyi: In the docx export I force free text to be placed between <p> tags. So I check if there are paragraphs and if not, I set them, so that always valid html is parsed (to be correct: I do this while parsing). I think this could be a way to solve this problem.

**Comment by tsiegleauq** [comment] 2016-09-28 12:54
there always is a solution :)
I currently try to do something similar with the HTMLValidizer facotry.
Rubbish in -> Valid HTML out.
Since this the HTML to PDF Parser should really be just that, I rather ensure it only receives valid HTML.

**Comment by emanuelschuetze** [comment] 2016-12-07 08:35
Exporting motion catalog pdf (imported by motion csv example) works for me with curent master.
@tsiegleauq Can we close this issue?

**Closed** 2016-12-14 10:00 UTC
Labels: bug, pdf
