### ISSUE TITLE
Tapping current election's yellow banner not working when already on some other elections page

### ISSUE THREAD

**Issue by f-fritz** [OpenSlides/OpenSlides#5667] opened 2020-11-02 20:36 UTC
**Describe the bug**
When already on some election's page the yellow banner at the top does not redirect to the active election but does nothing when being tapped.

**How to Reproduce**

1. Run an election
2. Stay on this election's page
3. Let the admin start a new election
4. The yellow banner appears - but tapping has no effect as I am already displaying some election. Even it it's not the active one.

**Expected behavior**
Jump to the exact election that is currently active

**System information**

- OpenSlides-Version: 3.3
- Commit: 7277a1bb01f02239a3b9a7cfa3aab61460940b22
- Server OS: Ubuntu server 20.04.1 LTS
- Docker version 19.03.13, build 4484c46d9d, docker-compose version 1.27.4, build 40524192
- Client Device: Mac Pro macOS 11.0 public beta, iPhone XS iOS 14.2 public beta
- Browser: Safari 14.0.1, Chrome 86.0.4240.111, Firefox 81.0.1, iOS Mobile Safari

**Comment by FinnStutzenstein** [comment] 2020-11-03 10:22
Duplicate of #5664

**Closed by FinnStutzenstein** 2020-11-03 10:22 UTC
Labels: bug
