### ISSUE TITLE
ignore m2m changes during migrations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4501] opened 2019-03-12 10:49 UTC
https://github.com/OpenSlides/OpenSlides/blob/d9369ab9c18e0d32aac2fe2e290b3d3b23d6c017/openslides/core/signals.py#L47

The new feature is a bit to good ;) During migrations (in my case 0007_superadmin.py, triggered with `admin.delete(skip_autoupdate=True)`), this singal handler gets called and tries to issue an autoupdate resulting in a complaining cache. Please add a check, if migrations are running and skip the m2m autoupdates. The traceback:
```
File "/home/finn/OpenSlides/OpenSlides/openslides/users/migrations/0007_superadmin.py", line 50, in create_superadmin_group
    admin.delete(skip_autoupdate=True)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/models.py", line 109, in delete
    return_value = super().delete(*args, **kwargs)  # type: ignore
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 880, in delete
    return collector.delete()
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/deletion.py", line 277, in delete
    sender=model, instance=obj, using=self.using
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/finn/OpenSlides/OpenSlides/openslides/core/signals.py", line 70, in autoupdate_for_many_to_many_relations
    reload=True,
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 155, in inform_changed_elements
    handle_changed_elements(elements.values())
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 256, in handle_changed_elements
    itertools.chain(elements, history_elements)
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/finn/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 209, in async_handle_collection_elements
    change_id = await update_cache(elements)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 202, in update_cache
    return await element_cache.change_elements(cache_elements)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/cache.py", line 135, in change_elements
    "Call element_cache.ensure_cache before changing elements."
RuntimeError: Call element_cache.ensure_cache before changing elements.
```

**Comment by emanuelschuetze** [comment] 2019-03-13 08:28
@normanjaeckel This is also a high priority issue... Would be great if you can fix it today.

**Comment by normanjaeckel** [comment] 2019-03-13 08:52
How can I reproduce this? I created a v2.3 database and migrated it successfully to master.

**Comment by FinnStutzenstein** [comment] 2019-03-13 08:56
[db.sqlite3.zip](https://github.com/OpenSlides/OpenSlides/files/2960556/db.sqlite3.zip)

This is my DB (I think from 2.3) that I always use. It happens there.

**Comment by emanuelschuetze** [comment] 2019-09-02 07:09
@normanjaeckel Can we close this issue?

**Comment by tsiegleauq** [comment] 2019-12-02 11:11
No answer and no reaction since September. Reopen if required.

**Closed by tsiegleauq** 2019-12-02 11:11 UTC
Labels: bug
