### ISSUE TITLE
Migration on new database fails (Django <= 2.1.4 && sqlite 3.26)

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#4063] opened 2018-12-14 10:19 UTC
Migrations fail on databases used at least since 2.3 after a recent system upgrade to sqlite 3.26 on ArchLinux systems.

`users.0007_superadmin` succeeds, after that, it fails.
<s>
motions/migrations/0017_remove_state_action_word.py seems to be the newest migration which may or not be the failing one.

Pointing at #4050 (merged yesterday)

edit: context: master branch, removing all personal data, then doing `paython manage.py createsettings; python manage.py migrate`
</s>

**Comment by MaximilianKrambach** [comment] 2018-12-14 10:43
There are two new migrations touched after the last working one was edited.
So #3975 is my new guess.

`./motions/migrations/0017_remove_state_action_word.py`
`./core/migrations/0009_auto_20181118_2126.py`

[freeze.txt](https://github.com/OpenSlides/OpenSlides/files/2679734/freeze.txt)
(databases not  uploadable by github)

**Comment by MaximilianKrambach** [comment] 2018-12-14 10:54
console output (extract)

<details>
<pre>
  Applying motions.0012_motion_comments... OK
  Applying motions.0013_motion_sorting_and_statute... OK
  Applying motions.0014_motionchangerecommendation_internal... OK
  Applying motions.0015_metadata_permission... OK
  Applying motions.0016_merge_amendment_into_final... OK
  Applying motions.0017_remove_state_action_word... OK
  Applying users.0007_superadmin... OK
Traceback (most recent call last):
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.motions_state_ _old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/openslides/openslides/_ _main_ _.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/_ _init_ _.py", line 381, in execute_from_command_line
    utility.execute()
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/_ _init_ _.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/openslides/openslides/core/management/commands/migrate.py", line 23, in handle
    super().handle(*args, **options)
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 226, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/openslides/.venv/lib/python3.7/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/openslides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/openslides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/openslides/openslides/motions/signals.py", line 18, in create_builtin_workflows
    workflow_1.save(skip_autoupdate=True)
  File "/openslides/openslides/motions/models.py", line 1202, in save
    super(Workflow, self).save(**kwargs)
  File "/openslides/openslides/utils/models.py", line 81, in save
    return_value = super().save(*args, **kwargs)  # type: ignore
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in _ _exit_ _
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/openslides/.venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.motions_state_ _old
</pre>
</details>

**Comment by emanuelschuetze** [comment] 2018-12-14 12:20
Now, I can reproduce the migrate error after upgrading my arch linux system! Works well before I updated today (`pip install openslides && openslides start --local-installation`). Does not work after upgrade... This is not a 3.0 issue.

``` 
...
django.db.utils.OperationalError: no such table: main.motions_state _old
```

**Comment by MaximilianKrambach** [comment] 2018-12-14 13:32
Just an idea, without having checked the migrations: A recent update in sqlite (3.25.3 -> 3.26) brought an API change in `alter table`[(link)](https://www.sqlite.org/draft/lang_altertable.html) which I don't inmediately understand. On my system I did the update on Dec. 4

**Comment by MaximilianKrambach** [comment] 2018-12-14 13:49
just confirmed: A manual downgrade of the system's sqlite-3.25.3-1 'repaired' openSlides.

**Comment by MaximilianKrambach** [comment] 2018-12-14 14:22
Fix in Django (not yet released, Version > 2.1.4): https://github.com/django/django/commit/c8ffdbe514b55ff5c9a2b8cb8bbdf2d3978c188f

Ticket:
https://code.djangoproject.com/ticket/30016

**Comment by FinnStutzenstein** [comment] 2018-12-14 17:22
@MaximilianKrambach very nice. Last week I traced this issue through django until the statement was issued to the sqlite library. In this point I stopped, because I didn't know how to debug more.

Do we know when django 2.1.4 will be released?

**Comment by emanuelschuetze** [comment] 2018-12-17 07:45
The sqlite-fix will be released in django 2.1.5 which is scheduled for 2019-01-01:
https://docs.djangoproject.com/en/2.1/releases/2.1.5/
(2.1.4 was released 2018-12-03)

**Comment by FinnStutzenstein** [comment] 2018-12-17 11:22
Ok. Because we won't release before this, we just add a notice into the readme, I guess. When the Django update is there, we should update the required version of Django.

**Comment by emanuelschuetze** [comment] 2019-01-07 08:46
Django 2.1.5 [was released last wee](https://docs.djangoproject.com/en/2.1/releases/2.1.5/).
Successfully tested with django 2.1.5 and sqlite 3.26 -> `python manage.py migrate` works now.
So you need django >=2.1.5 to run OpenSlides with sqlite >=3.26.x

**Comment by FinnStutzenstein** [comment] 2019-01-07 19:32
Maybe we should lock it int the requirements

**Comment by emanuelschuetze** [comment] 2019-01-08 08:21
Right, we should update in [production.txt](https://github.com/OpenSlides/OpenSlides/blob/master/requirements/production.txt#L5) django to >=2.1.5; <2.2
I'll do it.

**Comment by tsiegleauq** [comment] 2019-02-20 15:10
as discussed with @emanuelschuetze and after further discussion in #4090 we can close this

**Closed by tsiegleauq** 2019-02-20 15:10 UTC
Labels: bug
