### ISSUE TITLE
PDF of motions disrespects end of formatting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3097] opened 2017-03-19 13:50 UTC
This is the motion text:
![localhost 8000 2017-03-19 14-48-46](https://cloud.githubusercontent.com/assets/1828501/24081416/3563003c-0cb3-11e7-910f-82c0a9c28740.jpg)

And this is the PDF export of the motion:
[Antrag-W 2.pdf](https://github.com/OpenSlides/OpenSlides/files/853219/Antrag-W.2.pdf)

The bug is that only part of the paragraph is in red but in the PDF the whole paragraph is colored.

This bug might be a duplicate of #3095.

**Comment by emanuelschuetze** [comment] 2017-03-21 13:02
This is a duplicate of #2811

**Closed by emanuelschuetze** 2017-03-21 13:02 UTC
