### ISSUE TITLE
Error: too many SQL variables with big tables on sqlite

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#2812] opened 2017-01-04 19:14 UTC
Create 500 users:

```
python manage.py shell
from openslides.users.models import User
for i in range(500):
  User.objects.create_user("user{}".format(i + 1), "pass")
```
Then look at the users tab.

Workaround: Use Postgres or do not create 500 users

**Comment by emanuelschuetze** [comment] 2017-01-04 22:19
@ostcar Is this possible to fix for sqlite? Maybe you have to use a new bulk create function? But I think this shell error is not really a core bug.

**Comment by ostcar** [comment] 2017-01-04 23:38
The shell script was only a helper script to create 500 users. You can also create them with an csv-file or manual one by the time.

When you have created 500 users, then you can not see the user tab anymore.

**Comment by FinnStutzenstein** [comment] 2017-01-06 12:54
I cannot recreate this (I just added a `first_name="User{}".format(i + 1)` so the list is not empty). Tested with a fresh DB and sqlite. See screenshot:
![usertab](https://cloud.githubusercontent.com/assets/8439581/21718410/921c2fda-d417-11e6-9cab-38df65b3c834.jpg)

**Comment by normanjaeckel** [comment] 2017-01-10 22:21
Maybe change [this](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/collection.py#L336) to query.all() and filter missing ids inside the loop.

**Comment by emanuelschuetze** [comment] 2017-02-02 19:30
I can't reproduce this error. Tested with fresh db. With (cleared) redis and inmemory cache. With up to 3000 imported users. No problems to access to users tab.
I'll close this issue. If somebody can reproduce it with current master please reopen.

**Closed by emanuelschuetze** 2017-02-02 19:30 UTC
Labels: bug, high

**Comment by emanuelschuetze** [comment] 2017-02-02 20:21
BTW: Also with 5000 users no problem...
