### ISSUE TITLE
Check utils/main.py after mypy update

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3721] opened 2018-04-24 09:40 UTC
Since the update of mypy from 0.580 to 0.590 we need a `#type: ignore` in the [utils/main.py](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/main.py#L184). Is this correct?

**Comment by ostcar** [comment] 2018-05-06 12:04
I think it has nothing to do with the version of mypy, but with this commit: https://github.com/python/typeshed/commit/8009a34b908dc64c92c9fc073aefad9d0bf0dd43#diff-3b0653509570ddacc0238dabaa88c250

In the [typeshed-repo](https://github.com/python/typeshed) are a lot of type information for python libs, that don't have the type information in the code them self. 

Before that commit, mypy could not find any type information for `ctypes.WinDLL('shell32.dll')` and therefore used [`any`](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#the-any-type).

After that commit, mypy uses that stub file for the ctypes-lib. But `WinDLL` in only defined if `sys.platform == 'win32'`. Therefore there is no definition of `WinDLL` if mypy runs on linux.

I don't know if this is a bug. Therefore I opened an [issue](https://github.com/python/typeshed/issues/2099).

**Comment by ostcar** [comment] 2018-05-07 18:32
Ok, it is not a bug, but a feature (which I don't get...)

mypy test differently on different platforms. This is documented [here](http://mypy.readthedocs.io/en/latest/common_issues.html#python-version-and-system-platform-checks)

I don't understand why a statistic type analysis has to be platform dependent, but we can not change this.

I thing the best solution is the current solution. Another solution would be, to put the code inside of a `if sys.platform == "win32":` block and run mypy two times. Once with `--platform win32` and once with `--plattform linux`.

I would suggest, that we close this close this issue.

**Comment by emanuelschuetze** [comment] 2018-05-08 11:38
@FinnStutzenstein Ok for you that we close this issue?

**Closed** 2018-05-08 16:03 UTC
