### ISSUE TITLE
regression: motion PDF mangles text formatting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3059] opened 2017-03-06 22:57 UTC
- create a new motion (assure that you have set in the OS settings to number outside)
- now enable inline editing and add a word
- make the text color of the inserted text red
- strike through the word before the inserted one and make it green.
- save the change
- export the motion as PDF

result: while the motion looks like this:
![localhost 8000 2017-03-06 23-53-58](https://cloud.githubusercontent.com/assets/1828501/23633997/4f7fbca2-02c8-11e7-9eff-c072d0089cf5.jpg)
the pdf looks like this:
[Antrag-B1.pdf](https://github.com/OpenSlides/OpenSlides/files/822761/Antrag-B1.pdf)

So in the PDF the strike through is lost and ALL text is colored red not only one word.

**Comment by emanuelschuetze** [comment] 2017-03-07 07:49
This is a duplicate of #2811 .

**Closed by emanuelschuetze** 2017-03-07 07:49 UTC
