### ISSUE TITLE
Upgrading OpenSlides 4.0.1 fails (docker / openslides management tool)

### ISSUE THREAD

**Issue by tanjix** [OpenSlides/OpenSlides#6644] opened 2023-09-01 18:59 UTC
**Describe the bug**
Upgrading OpenSlides fails using the openslides self-service management tool

**How to Reproduce**
1. Shutdown openslides
2. Remove docker-compose.yml
3. Recreate config with lates openslides management self-service tool with "openslides config --config myconfig.yml ."
4. Run "docker-compose pull"
5. Run "docker-compose up -d"
6. Run "openslides migrations migrate -a a.b.c.d:443" (where a.b.c.d is my public ip address)

It then returns:

Progress:
Running migrations.
5 event migrations to apply.
No model migrations to apply.
Current migration index: 39
Position 1 from MI 39 to MI 44 ...
Position 2 from MI 39 to MI 44 ...
Position 3 from MI 39 to MI 44 ...
Position 4 from MI 39 to MI 44 ...
Position 1149 from MI 39 to MI 44 ...
Migration from MI 39 to MI 40 failed!

**System information**

- OpenSlides version: [e.g. 4.0]
- OS: Debian 11.6

**Comment by jsangmeister** [comment] 2023-09-05 09:49
Hi! It looks like the migration throws an exception which we currently do not log. I changed the code in https://github.com/OpenSlides/openslides-backend/pull/1893 to log all exceptions. You can build the image with the changes by following these steps (assuming you don't have the repo cloned already):
```
git clone --recurse-submodules git@github.com:OpenSlides/OpenSlides.git
cd OpenSlides
git submodule update --init
cd openslides-backend
git fetch origin pull/1893/head:log-migration-error
git checkout log-migration-error
../dev/docker/build.sh -D ghcr.io/openslides/openslides -t log-migration-error backend`
```
Afterwards, change the `backendManage` section of your config to use the new tag:
```
services:
  backendManage:
    tag: log-migration-error
```
Then, restart your server and try migrating again. This time, an error should be logged, which will hopefully provide some insight into why it occurs.

Alternatively, you can wait until the next release, where this fix will be included, and report the error then.

**Comment by tanjix** [comment] 2023-09-05 21:18
@jsangmeister I am not using the git version but only the dockerized version, which gets pulled through the openslides self-service management tool (https://github.com/OpenSlides/openslides-manage-service). I therefore assume, the steps you provided above won't work for me?

**Comment by jsangmeister** [comment] 2023-09-07 08:27
@tanjix Yes, they should: Docker matches images by name, no matter from where you pulled or built them. As long as you use a unique name like `log-migration-error`, docker should use your locally built image instead of the one from the management tool. If you run into any problems, please report back here; I did not manually test the steps.

**Comment by tanjix** [comment] 2023-09-17 21:26
Hi @jsangmeister

I get now the following output on the migration part as described above:

Progress:
exception: Model user/2 does not exist
output: |
  Running migrations.
  5 event migrations to apply.
  3 model migrations to apply.
  Current migration index: 39
  Position 1 from MI 39 to MI 44 ...
  Position 2 from MI 39 to MI 44 ...
  Position 3 from MI 39 to MI 44 ...
  Position 4 from MI 39 to MI 44 ...
  Position 1149 from MI 39 to MI 44 ...
  Migration from MI 39 to MI 40 failed!
stats: null
status: migration_required
success: true

Any advise would be appreciated!

Thank you!

**Comment by jsangmeister** [comment] 2023-09-26 07:51
It seems like some data is corrupt in your database. Migration 39 should not touch any user events and should therefore not complain about a missing `user/2`. Does your instance contain sensitive data or would it be possible to send a postgres dump to joshua.sangmeister@intevation.de? I'm afraid otherwise it will be next to impossible to debug this error.

**Comment by tanjix** [comment] 2023-10-11 19:04
I've sent you the dump two weeks ago. Have you had any chance yet to look into it? Thank you!

**Comment by jsangmeister** [comment] 2023-10-17 07:03
Hi, sorry for the missing reply. I've got the dump. Unfortunately, I'm pretty swamped right now, but I will look at it as soon as I get the opportunity!

**Comment by r-peschke** [comment] 2023-10-20 07:20
After importing the database dump, I got the error of inconsistent migration index (MI) between 27 and 39.
The last event(6903)(/position(1148) written to the database  was a login of user/2. This still has the MI 27.
Please change this in the database to 39. There are 2 ways to do this:
1. with psql directly in the database: 

    - check data: **select * from positions where position = 1148;** The column migration_index should have the value 27
    - **update positions set migration_index = 39 where position = 1148;**
    - Restart the application, at minimum the backend-service, to do the migration
2. You could do the change in your database dump. The line number refers to the dump you send us:

  - replace the 27 in line7140 by 39
  - replace the existing database by importing your dump
 - Restart the application, at minimum the backend-service, to do the migration

**Comment by tanjix** [comment] 2023-10-23 11:57
All done, the error remains:

```
output: |
  Running migrations.
  5 event migrations to apply.
  3 model migrations to apply.
  Current migration index: 39
  Position 1 from MI 39 to MI 44 ...
  Position 2 from MI 39 to MI 44 ...
  Position 3 from MI 39 to MI 44 ...
  Position 4 from MI 39 to MI 44 ...
  Position 1149 from MI 39 to MI 44 ...
  Migration from MI 39 to MI 40 failed!
stats: null
status: migration_required
success: true
```

Any other advise available? Thank you!

**Comment by jsangmeister** [comment] 2023-11-09 09:34
I finally got around to looking at your dump. It seems that your `positions` table is corrupt. Each database change creates a new position with an incremented id. Normally, all ids from 1 to your current position are present in the database. In your case, the positions 5-1148 are somehow missing. This was already indicated in your logs above, as these positions were not migrated at all, but I just assumed that you truncated the log... This is very likely not a bug in OpenSlides; did you tamper manually with your database at some point?

Anyway, to fix this, you need to recreate the missing positions. This should be possible with the following postgres command:
```
insert into positions overriding system value select i, now(), -1, null, 39 from generate_series(5,1148) as t(i);
```
Hope this fixes it for you as well!

**Closed** 2023-11-17 08:41 UTC
Labels: bug
