### ISSUE TITLE
regression: no longer possible to use image files in motions and agenda

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3032] opened 2017-03-02 01:05 UTC
Until OS 2.1 beta1 it was possible to add e.g. a JPG file to OS via the File menu.
After the addition to OS one could easily use these images: in a text field of e.g. a motion text one could click on the image icon and could choose in the list of uploaded images.

This feature is now missing. it is no longer possible to use an uploaded image.

**Comment by emanuelschuetze** [comment] 2017-03-03 08:13
Duplicate of #2924

**Closed by emanuelschuetze** 2017-03-03 08:13 UTC

**Comment by donovaly** [comment] 2017-03-04 14:18
> Duplicate of #2924

#2924 is about prohibiting external URLs, this bug is that one cannot use uploaded LOCAL images anymore.
For example in 2 weeks I have the opportunity to test OS in a party event and there I won't have Internet access. I cannot find a way to display an image in an agenda point. This is for me a major regression! So either I have overseen how this is done then please tell me otherwise please reopen this bug. If #2924 cannot or won't be solved, it should at least be possible to add an URL to the files uploaded to OS.

**Comment by emanuelschuetze** [comment] 2017-03-04 14:33
see #2924 please
