### ISSUE TITLE
All default config values are in database now

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3779] opened 2018-07-13 08:42 UTC
Create new database on current master.
See into db table 'core_configstore': All config keys/values are saved in this table! 
This is a regression which was intruduced by #3371.

Expected: Only changed config values should be saved in database. This would help us migrating configs; e.g. change default value or renaming. See e.g. #3768 where we added new configs for 'logo_available' which needs a migration file now.

@ostcar Can you look at this config issue please and try to restore the expected behaviour? You have changed the behaviour with #3371.

**Comment by ostcar** [comment] 2018-07-13 18:59
I don't see a solution.

The problem is, that any CollectionElement needs an id. This id has to be the same id then the pk field in the database. When a config value is not saved to the db, then there is not id and the config value can not be a CollectionElement.

Before the pull request, there where a lot of bugs and workarounds at any place at the code, that where special for core/config. For example:
https://github.com/OpenSlides/OpenSlides/pull/3371/files#diff-8bfadcb4bd744b1e4b747594f58bd16dL95
https://github.com/OpenSlides/OpenSlides/pull/3371/files#diff-308881b573529dea215cfa76e2e9d0b6L47
https://github.com/OpenSlides/OpenSlides/pull/3371/files#diff-308881b573529dea215cfa76e2e9d0b6L349

It could be possible, to make the config-name the primary-field in the database. (The last time I checked there is a [bug in the json field](https://github.com/dmkoch/django-jsonfield/issues/56) that prevented the name to be the primary key.) But this has another problem. It is very hard to typecheck the objects, when the id can either be a int or a string. So to fix this issue, you have also to change also all models in TypeScript. In all general code you have to thread the id as int or str.

So I would suggest, that you find another way to solve this. One possibility could be a special value. For example when the config value is "{'default'=True}", then the default value is used.

There is another problem. When the default value is localised and not in the database, then different clients with different language settings see different things on the projector.

**Comment by FinnStutzenstein** [comment] 2018-08-14 05:59
I suggest to leave it as it is now. Further changes make it more complicated. We just wondered, because we didn't noticed any changes in code that results in this behavoior of inserting everything into the DB and we didn't know that this was intended. You may close this issue, if you want.

**Closed** 2018-08-30 07:56 UTC
Labels: config
